# 1. DEPLOYMENT BACKEND
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kadastro-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kadastro-api
  template:
    metadata:
      labels:
        app: kadastro-api
    spec:
      containers:
      - name: api
        image: registry.ton-domaine.fr/kadastro-api:latest
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
# 2. DEPLOYMENT FRONTEND
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kadastro-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kadastro-ui
  template:
    metadata:
      labels:
        app: kadastro-ui
    spec:
      containers:
      - name: ui
        image: registry.ton-domaine.fr/kadastro-ui:latest
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
