---
# 3. INGRESS (L'aiguillage Traefik)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kadastro-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - host: kadastro.ton-domaine.fr
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: kadastro-api-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kadastro-ui-service
            port:
              number: 80